export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const LOGOUT_DELETE_DATA = 'LOGOUT_DELETE_DATA';

export const MODAL_TOGGLE = 'MODAL_TOGGLE';
export const BUY_MODAL_TOGGLE = 'BUY_MODAL_TOGGLE';
export const USER_DATA_MODAL_TOGGLE = 'USER_DATA_MODAL_TOGGLE';

export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const SET_ITEMS = 'SET_ITEMS';
export const ADDITIONAL_INFO_POST_START = 'ADDITIONAL_INFO_POST_START';
export const ADDITIONAL_INFO_POST_SUCCESS = 'ADDITIONAL_INFO_POST_SUCCESS';
export const ACCOUNT_SETTINGS_SET = 'ACCOUNT_SETTINGS_SET';

export const UPDATE_FAV = 'UPDATE_FAV';
export const RESET_FAV = 'RESET_FAV';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SUCC = 'FETCH_FAVORITES_SUCC';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const UPDATE_CART = "UPDATE_CART";

export const BUY_FAIL = "BUY_FAIL";
export const BUY_SUCCESS = "BUY_SUCCESS";
export const SET_ORDERS = "SET_ORDERS";

export const USER_DATA_CHANGE_STANDARD_SUCCESS = "USER_DATA_CHANGE_STANDARD_SUCCESS";
export const USER_DATA_CHANGE_STANDARD_FAIL = "USER_DATA_CHANGE_STANDARD_FAIL";
export const USER_DATA_CHANGE_EMAIL_SUCCESS = "USER_DATA_CHANGE_EMAIL_SUCCESS";
export const USER_DATA_CHANGE_EMAIL_FAIL = "USER_DATA_CHANGE_EMAIL_FAIL";
export const USER_DATA_CHANGE_PASSWORD_SUCCESS = "USER_DATA_CHANGE_PASSWORD_SUCCESS";
export const USER_DATA_CHANGE_PASSWORD_FAIL = "USER_DATA_CHANGE_PASSWORD_FAIL";

export const CHANGE_EMAIL = "CHANGE_EMAIL";
export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const CHECK_CREDENTIALS_SUCCESS = "CHECK_CREDENTIALS_SUCCESS";
export const CHECK_CREDENTIALS_FAIL = "CHECK_CREDENTIALS_FAIL";
export const CHANGE_EMAIL_IN_DB_STORAGE_SUCCESS = "CHANGE_EMAIL_IN_DB_STORAGE_SUCCESS";
export const CHANGE_EMAIL_IN_DB_STORAGE_FAIL = "CHANGE_EMAIL_IN_DB_STORAGE_FAIL";
export const SUCCESSFUL_CHANGE_CLOSE = "SUCCESSFUL_CHANGE_CLOSE";