export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';

export const MODAL_TOGGLE = 'MODAL_TOGGLE';

export const FETCH_ITEMS_FAIL = 'FETCH_ITEMS_FAIL';
export const SET_ITEMS = 'SET_ITEMS';
export const ADDITIONAL_INFO_POST_START = 'ADDITIONAL_INFO_POST_START';
export const ADDITIONAL_INFO_POST_SUCCESS = 'ADDITIONAL_INFO_POST_SUCCESS';
export const ACCOUNT_SETTINGS_SET = 'ACCOUNT_SETTINGS_SET';

export const UPDATE_FAV = 'UPDATE_FAV';
export const RESET_FAV = 'RESET_FAV';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const FETCH_FAVORITES_SUCC = 'FETCH_FAVORITES_SUCC';
export const FETCH_FAVORITES_FAIL = 'FETCH_FAVORITES_FAIL';

export const UPDATE_CART = "UPDATE_CART";